version: '3'

services:
  db:
    container_name: postgresql
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

volumes:
  database:
