FROM node

RUN mkdir -p /usr/src/app/backend

WORKDIR /usr/src/app/backend

COPY ./package*.json ./

RUN npm install

COPY . .

# RUN npx prisma migrate dev --name init

EXPOSE 3000

CMD ["npm", "start"]
