export { default as Chat } from './Chat/Chat'
export { default as Game } from './Game/Game'
export { default as Home } from  './Home/Home'
export { default as Login } from './Login/Login'
export { default as NotFound } from './NotFound/NotFound'
export { default as Profile } from './Profile/Profile'
export { default as Setting } from './Setting/Setting'
